/* eslint-disable react/react-in-jsx-scope */
import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <div>
      <Html>
        <Head>
          <title>
            Defiedge - Permissionless Liquidity Management on Uniswap v3
          </title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="preload"
            href="../public/fonts/GeneralSans-Regular.otf"
            as="font"
            type="font/otf"
            crossOrigin="anonymous"
          />

          <link
            rel="preload"
            href="../public/fonts/../public/fonts/GeneralSans-Medium.otf"
            as="font"
            type="font/otf"
            crossOrigin="anonymous"
          />

          <link
            rel="preload"
            href="../public/fonts/GeneralSans-Semibold.otf"
            as="font"
            type="font/otf"
            crossOrigin="anonymous"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    </div>
  );
}
